# linter: http://lint.travis-ci.org/
language: ruby
sudo: false
bundler_args: --without development
cache:
  bundler: true
  directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec puppet --version
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
env:
  global:
    - LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3.4.0"
    - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 2.7.0"
